name: firebase_db
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_database: ^11.3.5
  firebase_auth: ^5.5.2
  location: ^8.0.0
  cloud_firestore: ^5.6.6
  google_sign_in: ^6.3.0
  flutter_facebook_auth: ^7.1.1
  bloc: ^9.0.0
  equatable: ^2.0.7
  flutter_bloc: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
