// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_BwrIj5GyV3OfXT9ycCe6lzKPTXozLlM',
    appId: '1:359710256279:web:bea49c380a01760918cdd2',
    messagingSenderId: '359710256279',
    projectId: 'fir-db-799ca',
    authDomain: 'fir-db-799ca.firebaseapp.com',
    storageBucket: 'fir-db-799ca.firebasestorage.app',
    measurementId: 'G-1E6ZHJHYWY',
    databaseURL: 'https://fir-db-81cb1-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzWCz6h9TZbpsxFePJJIsbq0FiG_OWLjs',
    appId: '1:359710256279:android:07e6b8be980fb9a918cdd2',
    messagingSenderId: '359710256279',
    projectId: 'fir-db-799ca',
    storageBucket: 'fir-db-799ca.firebasestorage.app',
    databaseURL: 'https://fir-db-81cb1-default-rtdb.firebaseio.com',
  );
}
